### ISSUE TITLE
Plugin crash after login

### ISSUE THREAD

**Issue by Overlord23** [pe2mbs/ajenti-mdadm#1]
Hi,

First bug report!
I'm running Ajenti v1.2.22.21 on Raspbian; after logging into Ajenti, MDADM plugin crashes.
I started Ajenti in debug mode and found this:

    Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.7/ajenti/plugins/main/main.py", line 346, in init
        cat = cls.new(self.ui)
      File "/usr/lib/pymodules/python2.7/ajenti/api/__init__.py", line 91, in new
        return context.instantiate(cls, *args, **kwargs)
      File "/usr/lib/pymodules/python2.7/ajenti/plugins/__init__.py", line 202, in instantiate
        init(instance)
      File "/var/lib/ajenti/plugins/mdadm/main.py", line 77, in init
        self.mdadm.Update()
      File "/var/lib/ajenti/plugins/mdadm/api.py", line 409, in Update
        del lines[0]
    IndexError: list assignment index out of range

I got your plugin installed on Debian Wheezy x86 and doesn't crash like on Raspian.
It could be a problem with some Python library or module?

**Comment by pe2mbs** [comment]
Hi  Overlord23,

It seems that on raspbian the command  #mdadm --detail-platform doesn't give result. can you execute that command on it and paste here the result of it.

I'll fix the code tonight (CET) to make the code more stable.

**Comment by Overlord23** [comment]
Do you mean run it under Debian x86?
I executed the command under Raspbian but it dind't give me any result too.
On Debian x86 I got this output:
 
    mdmon: imsm capabilities not found for controller: /sys/devices/pci0000:00/0000:00:0d.0 (type SATA)

**Comment by pe2mbs** [comment]
Ok, as it seems that whenever there is no SATA controller this is the expected behavior of mdadm. Therefore I changed to code to check if there is any result passed back fro mdadm, if not the IO controller value is set to 'unknown'.
